import { Document, Packer, Paragraph, TextRun, HeadingLevel } from "docx";
import { saveAs } from "file-saver";
import type { TraceStep } from "./types";

/** Build the full report markdown: findings + audit trail appendix. */
function buildFullReport(report: string, steps: TraceStep[], question: string): string {
  const lines: string[] = [];

  // Header
  lines.push("# BioAgent Investigation Report");
  lines.push("");
  lines.push(`**Question:** ${question}`);
  lines.push(`**Date:** ${new Date().toISOString().slice(0, 10)}`);
  lines.push(`**Tool calls:** ${steps.filter(s => s.tool_call).length}`);
  lines.push(`**Total steps:** ${steps.length}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Phase outputs: research summary and investigation plan
  const researchStep = [...steps].reverse().find(s => s.phase === "research" && !s.tool_call);
  const planStep = [...steps].reverse().find(s => s.phase === "plan" && !s.tool_call);

  if (researchStep) {
    lines.push("## Research Summary");
    lines.push("");
    lines.push(researchStep.reasoning);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  if (planStep) {
    lines.push("## Investigation Plan");
    lines.push("");
    lines.push(planStep.reasoning);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  // Final report (from synthesis agent)
  lines.push("## Synthesis");
  lines.push("");
  lines.push(report);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Audit trail
  lines.push("## Appendix: Audit Trail");
  lines.push("");
  lines.push("Every tool call made during this investigation, with reproducible queries.");
  lines.push("");

  const toolSteps = steps.filter(s => s.tool_call);
  for (const step of toolSteps) {
    const tc = step.tool_call!;
    lines.push(`### Step ${step.step_number}: ${tc.tool_name}`);
    lines.push("");
    lines.push(`- **Phase:** ${step.phase}`);
    lines.push(`- **Duration:** ${tc.duration_ms}ms`);
    lines.push(`- **Result:** ${tc.output_summary}`);
    lines.push(`- **Reproducible query:**`);
    lines.push("```");
    lines.push(tc.reproducible_query);
    lines.push("```");
    lines.push("");
  }

  // Data sources — derived from actual tool calls
  lines.push("## Appendix: Data Sources");
  lines.push("");
  const sourceUsage = buildSourceUsage(toolSteps);
  if (sourceUsage.length > 0) {
    lines.push("| Source | Queries | Data Returned |");
    lines.push("|--------|---------|---------------|");
    for (const row of sourceUsage) {
      lines.push(`| ${row.source} | ${row.queries} | ${row.summary} |`);
    }
  } else {
    lines.push("No tool calls were made during this investigation.");
  }
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("*Generated by [BioAgent](https://bioagent.eu). All findings are derived from tool call results. Agent interpretations are clearly distinguished from raw data.*");

  return lines.join("\n");
}

const SOURCE_MAP: Record<string, string> = {
  query_alphaseq_bindings: "AlphaSeq",
  query_sabdab: "SAbDab",
  query_chembl: "ChEMBL",
  run_statistics: "Statistics",
};

interface SourceRow {
  source: string;
  queries: number;
  summary: string;
}

/** Build per-source usage summary from actual tool call results. */
function buildSourceUsage(toolSteps: TraceStep[]): SourceRow[] {
  const grouped: Record<string, { count: number; summaries: string[] }> = {};

  for (const step of toolSteps) {
    const tc = step.tool_call!;
    const source = SOURCE_MAP[tc.tool_name] ?? tc.tool_name;
    if (!grouped[source]) {
      grouped[source] = { count: 0, summaries: [] };
    }
    grouped[source].count += 1;
    grouped[source].summaries.push(tc.output_summary);
  }

  return Object.entries(grouped).map(([source, { count, summaries }]) => ({
    source,
    queries: count,
    summary: summaries.join("; "),
  }));
}

/** Download the report as a .md file. */
export function exportMarkdown(report: string, steps: TraceStep[], question: string): void {
  const full = buildFullReport(report, steps, question);
  const blob = new Blob([full], { type: "text/markdown;charset=utf-8" });
  saveAs(blob, "bioagent-report.md");
}

/** Download the report as a .docx file. */
export async function exportDocx(report: string, steps: TraceStep[], question: string): Promise<void> {
  const full = buildFullReport(report, steps, question);
  const paragraphs = markdownToParagraphs(full);
  const doc = new Document({
    sections: [{ children: paragraphs }],
  });
  const blob = await Packer.toBlob(doc);
  saveAs(blob, "bioagent-report.docx");
}

/** Simple markdown-to-docx paragraph converter. */
function markdownToParagraphs(md: string): Paragraph[] {
  const lines = md.split("\n");
  const paragraphs: Paragraph[] = [];

  for (const line of lines) {
    if (line.startsWith("# ")) {
      paragraphs.push(
        new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: line.slice(2), bold: true })] }),
      );
    } else if (line.startsWith("## ")) {
      paragraphs.push(
        new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text: line.slice(3), bold: true })] }),
      );
    } else if (line.startsWith("### ")) {
      paragraphs.push(
        new Paragraph({ heading: HeadingLevel.HEADING_3, children: [new TextRun({ text: line.slice(4), bold: true })] }),
      );
    } else if (line.startsWith("- ")) {
      paragraphs.push(
        new Paragraph({ bullet: { level: 0 }, children: inlineRuns(line.slice(2)) }),
      );
    } else if (line === "---") {
      paragraphs.push(new Paragraph({ thematicBreak: true }));
    } else if (line.startsWith("```")) {
      // skip code fences, content lines handled as plain text
    } else if (line.startsWith("|")) {
      // Table row - render as plain text in docx
      const cells = line.split("|").filter(c => c.trim() && !c.match(/^[-\s]+$/));
      if (cells.length > 0) {
        paragraphs.push(new Paragraph({ children: [new TextRun({ text: cells.map(c => c.trim()).join("  |  "), font: "Courier New", size: 18 })] }));
      }
    } else if (line.trim() === "") {
      paragraphs.push(new Paragraph({}));
    } else {
      paragraphs.push(new Paragraph({ children: inlineRuns(line) }));
    }
  }

  return paragraphs;
}

/** Parse bold (**text**) and code (`text`) into TextRuns. */
function inlineRuns(text: string): TextRun[] {
  const runs: TextRun[] = [];
  const pattern = /(\*\*(.+?)\*\*|`(.+?)`)/g;
  let last = 0;

  for (const match of text.matchAll(pattern)) {
    const idx = match.index ?? 0;
    if (idx > last) {
      runs.push(new TextRun({ text: text.slice(last, idx) }));
    }
    if (match[2]) {
      runs.push(new TextRun({ text: match[2], bold: true }));
    } else if (match[3]) {
      runs.push(new TextRun({ text: match[3], font: "Courier New", size: 20 }));
    }
    last = idx + match[0].length;
  }

  if (last < text.length) {
    runs.push(new TextRun({ text: text.slice(last) }));
  }

  return runs.length > 0 ? runs : [new TextRun({ text })];
}
